# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spaceship.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fspaceship.proto\">\n\x07Officer\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x0c\n\x04rank\x18\x03 \x01(\t\"\xa6\x01\n\tSpaceship\x12\x1d\n\talignment\x18\x01 \x01(\x0e\x32\n.Alignment\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1e\n\nship_class\x18\x03 \x01(\x0e\x32\n.ShipClass\x12\x0e\n\x06length\x18\x04 \x01(\x02\x12\x11\n\tcrew_size\x18\x05 \x01(\x05\x12\r\n\x05\x61rmed\x18\x06 \x01(\x08\x12\x1a\n\x08officers\x18\x07 \x03(\x0b\x32\x08.Officer\"2\n\x0b\x43oordinates\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01* \n\tAlignment\x12\x08\n\x04\x41LLY\x10\x00\x12\t\n\x05\x45NEMY\x10\x01*`\n\tShipClass\x12\x0c\n\x08\x43ORVETTE\x10\x00\x12\x0b\n\x07\x46RIGATE\x10\x01\x12\x0b\n\x07\x43RUISER\x10\x02\x12\r\n\tDESTROYER\x10\x03\x12\x0b\n\x07\x43\x41RRIER\x10\x04\x12\x0f\n\x0b\x44READNOUGHT\x10\x05\x32?\n\x10SpaceshipService\x12+\n\rGetSpaceships\x12\x0c.Coordinates\x1a\n.Spaceship0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spaceship_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ALIGNMENT']._serialized_start=304
  _globals['_ALIGNMENT']._serialized_end=336
  _globals['_SHIPCLASS']._serialized_start=338
  _globals['_SHIPCLASS']._serialized_end=434
  _globals['_OFFICER']._serialized_start=19
  _globals['_OFFICER']._serialized_end=81
  _globals['_SPACESHIP']._serialized_start=84
  _globals['_SPACESHIP']._serialized_end=250
  _globals['_COORDINATES']._serialized_start=252
  _globals['_COORDINATES']._serialized_end=302
  _globals['_SPACESHIPSERVICE']._serialized_start=436
  _globals['_SPACESHIPSERVICE']._serialized_end=499
# @@protoc_insertion_point(module_scope)
